apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - namespace.yaml
namespace: cruise
images:
  - name: yny.ocir.io/axlgn2n9ijoa/jeju-cruise/front
    newTag: prod-7
