apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: doreme-dev
patches:
  - target:
      kind: Deployment
      name: doreme
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
