apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - namespace.yaml
namespace: onedayflex
images:
  - name: yny.ocir.io/axlgn2n9ijoa/onedayflex/front
    newTag: prod-12
