apiVersion: v1
kind: ConfigMap
metadata:
  name: leeshvideo-back-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://heatwave-mysql.subnetprivate02.armvcn.oraclevcn.com:3306/leeshvideo_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  PUBLIC_BASE_URL: "https://api.dev.leeshvideo.klr.kr"
  ASSETS_DIR: "/app/data/assets"
  DATA_SUBPATH: "leeshvideo-dev"
  TOSS_API_BASE_URL: "https://apps-in-toss-api.toss.im"
  TOSS_SSL_BUNDLE: ""
  PROVIDER_CALLBACK_ENABLED: "false"
