apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doreme
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - doreme.klr.kr
      secretName: doreme-klr-kr-tls
  rules:
    - host: doreme.klr.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: doreme
                port:
                  number: 8080
