apiVersion: v1
kind: Service
metadata:
  name: gakhalmo-front-dev
  namespace: gakhalmo-dev
spec:
  selector:
    app: gakhalmo-front-dev
  ports:
    - name: http
      port: 3000
      targetPort: 3000
