apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-nfs
  namespace: mail
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: mail-nfs
