apiVersion: v1
kind: ConfigMap
metadata:
  name: snappymail-domain-config
  namespace: mail
data:
  klr.kr.json: |
    {
        "IMAP": {
            "host": "mail-server.mail.svc.cluster.local",
            "port": 143,
            "type": 0,
            "timeout": 300,
            "shortLogin": true,
            "lowerLogin": true,
            "sasl": [
                "PLAIN",
                "LOGIN"
            ],
            "ssl": {
                "verify_peer": false,
                "verify_peer_name": false,
                "allow_self_signed": true,
                "SNI_enabled": true,
                "disable_compression": true,
                "security_level": 0
            },
            "disabled_capabilities": [],
            "use_expunge_all_on_delete": false,
            "fast_simple_search": true,
            "force_select": false,
            "message_all_headers": false,
            "message_list_limit": 10000,
            "search_filter": ""
        },
        "SMTP": {
            "host": "mail-server.mail.svc.cluster.local",
            "port": 587,
            "type": 0,
            "timeout": 60,
            "shortLogin": true,
            "lowerLogin": true,
            "sasl": [
                "PLAIN",
                "LOGIN"
            ],
            "ssl": {
                "verify_peer": false,
                "verify_peer_name": false,
                "allow_self_signed": true,
                "SNI_enabled": true,
                "disable_compression": true,
                "security_level": 0
            },
            "useAuth": true,
            "setSender": false,
            "usePhpMail": false
        },
        "Sieve": {
            "host": "mail-server.mail.svc.cluster.local",
            "port": 4190,
            "type": 0,
            "timeout": 10,
            "shortLogin": false,
            "lowerLogin": true,
            "sasl": [
                "PLAIN",
                "LOGIN"
            ],
            "ssl": {
                "verify_peer": false,
                "verify_peer_name": false,
                "allow_self_signed": true,
                "SNI_enabled": true,
                "disable_compression": true,
                "security_level": 0
            },
            "enabled": false
        },
        "whiteList": ""
    }
