apiVersion: v1
kind: Service
metadata:
  name: doreme
  labels:
    app.kubernetes.io/name: doreme
spec:
  selector:
    app.kubernetes.io/name: doreme
  ports:
    - name: http
      port: 8080
      targetPort: http
