controller:
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    proxy-real-ip-cidr: "10.0.20.0/24"
    use-proxy-protocol: "true"
  service:
    annotations:
      oci.oraclecloud.com/load-balancer-type: "lb"
      service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.ap-chuncheon-1.aaaaaaaafzd46zbvuwujq2snymzafgpvwirvmzptikor6tfvfgn72bvwfrba"
      service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
      service.beta.kubernetes.io/oci-load-balancer-connection-proxy-protocol-version: "2"
    externalTrafficPolicy: Local
  admissionWebhooks:
    enabled: false
