apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-nfs
  namespace: wireguard
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: wireguard-nfs
