---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # ArgoCD Server URL (matches your ingress)
  url: https://argocd.klr.kr

  # Enable anonymous access (set to "false" for production)
  users.anonymous.enabled: "false"

  # Admin enabled
  admin.enabled: "true"

  # Git repository timeout
  timeout.reconciliation: 180s

  # Application resync interval (default: 3m)
  timeout.reconciliation: 180s

  # Repository credentials template (for private repos)
  # Uncomment and configure for private Git repositories
  # repositories: |
  #   - url: https://github.com/your-org/your-repo
  #     passwordSecret:
  #       name: github-secret
  #       key: password
  #     usernameSecret:
  #       name: github-secret
  #       key: username

  # Helm repositories
  # helm.repositories: |
  #   - url: https://charts.bitnami.com/bitnami
  #     name: bitnami
  #   - url: https://kubernetes.github.io/ingress-nginx
  #     name: ingress-nginx

  # Resource customizations for health checks
  resource.customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs

  # Kustomize build options
  kustomize.buildOptions: --enable-helm

  # Diff customizations
  resource.compareoptions: |
    ignoreAggregatedRoles: true

  # Enable Dex (SSO) - optional
  # dex.config: |
  #   connectors:
  #     - type: github
  #       id: github
  #       name: GitHub
  #       config:
  #         clientID: $GITHUB_CLIENT_ID
  #         clientSecret: $GITHUB_CLIENT_SECRET
  #         orgs:
  #         - name: your-org

  # Status badge enabled
  statusbadge.enabled: "true"

  # Exec enabled for debugging
  exec.enabled: "false"

  # Accounts configuration
  # accounts.alice: apiKey, login
  # accounts.bob: apiKey

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy (deny all)
  policy.default: role:readonly

  # RBAC policy
  policy.csv: |
    # Grant admin role full permissions
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, certificates, *, *, allow

    # Grant developer role application permissions
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, applications, override, */*, allow
    p, role:developer, applications, update, */*, allow

    # Grant readonly role
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, clusters, get, *, allow

    # Assign admin role to built-in admin user
    g, admin, role:admin

  # SSO RBAC (example with GitHub teams)
  # scopes: '[groups, email]'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Server insecure mode (TLS termination at ingress)
  server.insecure: "true"

  # Disable admin user (after setting up SSO)
  # server.disable.admin: "false"

  # Application controller parallelism
  application.controller.status.processors: "20"
  application.controller.operation.processors: "10"

  # Repo server parallelism
  reposerver.parallelism.limit: "10"
