---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: https://github.com/leestana01/gitops
    targetRevision: develop
    path: k8s/overlays/development

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # HPA가 관리하는 경우

  # Notification annotations
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: "engineering"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "engineering"
