apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: shared-nfs
