apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml
  - namespace.yaml
namespace: travelfood-dev
nameSuffix: -dev
images:
  - name: yny.ocir.io/axlgn2n9ijoa/travelfood/web
    newTag: dev-2
