apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-nfs
  namespace: redis
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: redis-nfs
