apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
namespace: leeshvideo
images:
  - name: yny.ocir.io/axlgn2n9ijoa/leeshvideo/admin
    newTag: prod-10
