apiVersion: v1
kind: Service
metadata:
  name: leeshvideo-admin
  labels:
    app: leeshvideo-admin
spec:
  selector:
    app: leeshvideo-admin
  ports:
    - name: http
      port: 80
      targetPort: 80
