apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gakhalmo-back-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/leestana01/gitops.git
    targetRevision: main
    path: apps/gakhalmo-back-dev/base

  destination:
    server: https://kubernetes.default.svc
    namespace: gakhalmo-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
